version: 2
updates:
  - package-ecosystem: nuget
    directory: /Source
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[REPO]"

  - package-ecosystem: nuget
    directory: /tools/B13ProductionModelReceipts
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[REPO]"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[REPO]"
